#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_TEST_USER
		WITH PASSWORD '$POSTGRES_TEST_PASSWORD';

	CREATE DATABASE $POSTGRES_TEST_DB;

	GRANT ALL PRIVILEGES
		ON DATABASE $POSTGRES_TEST_DB
		TO $POSTGRES_TEST_USER;
EOSQL
