version: "3"

networks:
  devcontainer:
    driver: bridge

services:
  authentication:
    image: bhongy/vscode-remote-devcontainer.go
    env_file: .env
    volumes:
      # go module cache, to avoid dependencies re-download on container rebuilds
      - gomod-cache:/go/pkg/mod/cache
      # we need to mount at the root so `.git` is included
      - ../..:/workspaces/kimidori:delegated
    networks:
      - devcontainer
    command: sleep infinity

    # security and capability needed for ptrace-based debugger for golang
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    depends_on:
      - database

  database:
    image: postgres:12.4-alpine
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./create-testdb.sh
        target: /docker-entrypoint-initdb.d/01-create-testdb.sh
        read_only: true
    networks:
      - devcontainer
    restart: unless-stopped
    # use user created in postgres image instead of root
    user: postgres

volumes:
  gomod-cache:
  postgres-data:
