version: '3'

networks:
  default:
    external: true
    name: kimidori-devcontainer

services:
  app:
    # cannot use alpine. we need git, etc in dev
    image: node:16.13.1-bullseye
    volumes:
      # we need to mount at the root so `.git` is included
      - ../../:/kimidori
      # persist node_modules on container rebuilds
      - node_modules:/kimidori/app/node_modules
      # parcel cache
      - parcel-cache:/kimidori/app/.parcel-cache
      # parcel build output folder
      - dist:/kimidori/app/dist
    stdin_open: true
    tty: true

volumes:
  node_modules:
  parcel-cache:
  dist:
