apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kimidori.local

nodes:
- role: control-plane
- role: worker
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
  extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   protocol: TCP
  # - containerPort: 443
  #   hostPort: 443
  #   protocol: TCP
  # allow hitting the cluster from local machine via http://localhost:8020
  # - containerPort: 8020
  - containerPort: 30820 # k8s needs node port to be between 30000-32767
    hostPort: 8020
    protocol: TCP
  extraMounts:
  - hostPath: ./html
    containerPath: /root/simple-nginx/html
# - role: worker
# - role: worker
