version: "3"
services:
  consul-server:
    image: consul:1.10.3
    container_name: kimidori-local-consul-server
    command: agent
    volumes:
    - ./config/consul-server.json:/consul/config/server.json:ro
    - ./secrets/certs:/consul/config/certs:ro
    networks:
    - kimidori.local
    ports:
    - "8500:8500"
    - "8600:8600/tcp"
    - "8600:8600/udp"
    restart: always

networks:
  kimidori.local:
    name: kimidori.local
    driver: bridge
