# Generate TLS certificates for consul server
#
# docker-compose -f gen-secrets.docker-compose.yaml run --rm ca
# docker-compose -f gen-secrets.docker-compose.yaml run --rm server-cert

version: '3.7'
services:
  ca:
    image: consul:1.10.3
    working_dir: /out
    volumes:
    - ./secrets:/out
    command: tls ca create
    # command: 'tls ca create -domain="kimidori.local"'
  server-cert:
    image: consul:1.10.3
    working_dir: /out
    volumes:
    - ./secrets:/out
    command: tls cert create -server
    # command: 'tls cert create -server -dc="kimidori.local" -domain="kimidori.local"'
